// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.2
//   protoc               v6.31.1
// source: common.proto

/* eslint-disable */

export const protobufPackage = "";

export interface Empty {
}

export const _PACKAGE_NAME = "";
